using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Historia
{
	/// <summary>
	/// Provides references for packet structures.
	/// </summary>
	public class Op
	{
		/// <summary>
		/// Represents unique properties of a recognized packet.
		/// </summary>
		public class Opcode
		{
			public string name;
			public int size;
			public short header;
		}

		/// <summary>
		/// List of recognized opcodes in game. Not complete.
		/// </summary>
		#region opcodes
		public static readonly List<Opcode> opcodes = new List<Opcode>()
		{
			new Opcode { name = "CB_LOGIN", header = 0x03, size =  206},
			new Opcode { name = "CB_LOGIN_BY_PASSPORT", header = 0x04, size =  1131},
			new Opcode { name = "CB_LOGOUT", header = 0x05, size =  10},
			new Opcode { name = "CB_START_BARRACK", header = 0x06, size =  11},
			new Opcode { name = "CB_COMMANDER_CREATE", header = 0x07, size =  93},
			new Opcode { name = "BC_COMMANDER_CREATE_SLOTID", header = 0x08, size =  7},
			new Opcode { name = "CB_COMMANDER_DESTROY", header = 0x09, size =  18},
			new Opcode { name = "CB_CHECK_CLIENT_INTEGRITY", header = 0x0A, size =  74},
			new Opcode { name = "CB_CLIENT_INTEGRITY_FAIL", header = 0x0B, size =  1035},
			new Opcode { name = "CB_START_GAME", header = 0x0C, size =  13},
			new Opcode { name = "CB_BARRACKNAME_CHANGE", header = 0x0D, size =  74},
			new Opcode { name = "CB_COMMANDER_MOVE", header = 0x0E, size =  31},
			new Opcode { name = "CB_ECHO", header = 0x0F, size =  30},
			new Opcode { name = "BC_LOGINOK", header = 0x10, size =  129},
			new Opcode { name = "BC_LOGIN_PACKET_RECEIVED", header = 0x11, size =  6},
			new Opcode { name = "BC_LOGOUTOK", header = 0x12, size =  6},
			new Opcode { name = "BC_COMMANDER_LIST", header = 0x13, size =  0},
			new Opcode { name = "BC_COMMANDER_CREATE", header = 0x14, size =  342},
			new Opcode { name = "BC_COMMANDER_DESTROY", header = 0x15, size =  7},
			new Opcode { name = "BC_START_GAMEOK", header = 0x16, size =  33},
			new Opcode { name = "BC_SINGLE_INFO", header = 0x17, size =  325},
			new Opcode { name = "BC_MESSAGE", header = 0x18, size =  0},
			new Opcode { name = "BC_ECHO", header = 0x19, size =  26},
			new Opcode { name = "BC_MYPAGE_MAP", header = 0x1A, size =  0},
			new Opcode { name = "BC_BARRACKNAME_CHANGE", header = 0x1B, size =  75},
			new Opcode { name = "CB_IES_MODIFY_INFO", header = 0x32, size =  0},
			new Opcode { name = "BC_IES_MODIFY_INFO", header = 0x33, size =  0},
			new Opcode { name = "BC_IES_MODIFY_LIST", header = 0x34, size =  0},
			new Opcode { name = "CB_IES_REVISION_DELETE", header = 0x35, size =  0},
			new Opcode { name = "BC_IES_REVISION_DELETE", header = 0x36, size =  0},
			new Opcode { name = "CB_SCREENSHOT_HASH", header = 0x37, size =  42},
			new Opcode { name = "CB_REQ_CHANNEL_TRAFFIC", header = 0x38, size =  14},
			new Opcode { name = "CB_VISIT", header = 0x39, size =  74},
			new Opcode { name = "CB_BUY_THEMA", header = 0x3A, size =  22},
			new Opcode { name = "BC_ACCOUNT_PROP", header = 0x3B, size =  0},
			new Opcode { name = "CB_CURRENT_BARRACK", header = 0x3C, size =  39},
			new Opcode { name = "BC_NORMAL", header = 0x3D, size =  0},
			new Opcode { name = "CB_POSE", header = 0x3E, size =  15},
			new Opcode { name = "CB_PLACE_CMD", header = 0x3F, size =  46},
			new Opcode { name = "CB_CHAT", header = 0x40, size =  0},
			new Opcode { name = "BC_CHAT", header = 0x41, size =  0},
			new Opcode { name = "CB_ECHO_NORMAL", header = 0x42, size =  0},
			new Opcode { name = "CB_REQ_SLOT_PRICE", header = 0x43, size =  10},
			new Opcode { name = "BC_REQ_SLOT_PRICE", header = 0x44, size =  10},
			new Opcode { name = "CB_CHANGE_BARRACK_LAYER", header = 0x45, size =  22},
			new Opcode { name = "CB_SELECT_BARRACK_LAYER", header = 0x46, size =  14},
			new Opcode { name = "CB_JUMP", header = 0x47, size =  19},
			new Opcode { name = "BC_JUMP", header = 0x48, size =  19},
			new Opcode { name = "BC_SERVER_ENTRY", header = 0x49, size =  18},
			new Opcode { name = "CB_PET_PC", header = 0x4A, size =  26},
			new Opcode { name = "CB_PET_COMMAND", header = 0x4B, size =  27},
			new Opcode { name = "CB_REQ_CHANGE_POSTBOX_STATE", header = 0x4C, size =  23},
			new Opcode { name = "CB_REQ_GET_POSTBOX_ITEM", header = 0x4D, size =  1051},
			new Opcode { name = "CB_REQ_POSTBOX_PAGE", header = 0x4E, size =  14},
			new Opcode { name = "BC_WAIT_QUEUE_ORDER", header = 0x4F, size =  10},
			new Opcode { name = "CB_CANCEL_SERVER_WAIT_QUEUE", header = 0x50, size =  10},
			new Opcode { name = "CB_NGS", header = 0x51, size =  0},
			new Opcode { name = "CB_GEMSCOOL_PCINFO", header = 0x52, size =  1290},
			new Opcode { name = "CB_NOT_AUTHORIZED_ADDON_LIST", header = 0x53, size =  1039},
			new Opcode { name = "ZC_TREASUREMARK_LIST_MAP", header = 0x0D7, size =  0},
			new Opcode { name = "CS_LOGIN", header = 0x0B55, size =  64},
			new Opcode { name = "SC_NORMAL", header = 0x0B56, size =  0},
			new Opcode { name = "SC_FROM_INTEGRATE", header = 0x0B57, size =  0},
			new Opcode { name = "CS_REGISTER_SNS_ID", header = 0x0B58, size =  16},
			new Opcode { name = "CS_REQ_SNS_PC_INFO", header = 0x0B59, size =  0},
			new Opcode { name = "CS_REQ_ADD_FRIEND", header = 0x0B5A, size =  70},
			new Opcode { name = "CS_REQ_BLOCK_FRIEND", header = 0x0B5B, size =  70},
			new Opcode { name = "CS_FRIEND_CMD", header = 0x0B5C, size =  24},
			new Opcode { name = "CS_FRIEND_SET_ADDINFO", header = 0x0B5D, size =  160},
			new Opcode { name = "CS_CHAT", header = 0x0B5E, size =  0},
			new Opcode { name = "CS_GROUP_CHAT_INVITE", header = 0x0B5F, size =  110},
			new Opcode { name = "CS_GROUP_CHAT_INVITE_BY_TAG", header = 0x0B60, size =  22},
			new Opcode { name = "CS_ALLOW_GROUP_CHAT_TAG_INVITE", header = 0x0B61, size =  46},
			new Opcode { name = "CS_REFRESH_GROUP_CHAT", header = 0x0B62, size =  6},
			new Opcode { name = "CS_CREATE_GROUP_CHAT", header = 0x0B63, size =  6},
			new Opcode { name = "CS_REQ_CHAT_HISTORY", header = 0x0B64, size =  22},
			new Opcode { name = "CS_REQ_OUT_ROOM", header = 0x0B65, size =  14},
			new Opcode { name = "CS_REQ_RELATED_PC_SESSION", header = 0x0B66, size =  16},
			new Opcode { name = "CS_REDIS_SKILLPOINT", header = 0x0B67, size =  22},
			new Opcode { name = "CS_PARTY_CLIENT_INFO_SEND", header = 0x0B68, size =  0},
			new Opcode { name = "CS_NORMAL_GAME_START", header = 0x0B69, size =  6},
			new Opcode { name = "CS_REQUEST_PVP_RANKING", header = 0x0B6A, size =  88},
			new Opcode { name = "CS_REQUEST_ALL_SEASON_TOP_PVP_RANKING", header = 0x0B6B, size =  80},
			new Opcode { name = "CS_INVITE_PARTY_PVP", header = 0x0B6C, size =  10},
			new Opcode { name = "CS_ACCEPT_PARTY_PVP", header = 0x0B6D, size =  19},
			new Opcode { name = "CS_LIKE_IT", header = 0x0B6E, size =  88},
			new Opcode { name = "CS_UNLIKE_IT", header = 0x0B6F, size =  24},
			new Opcode { name = "CS_LIKE_IT_CONFIRM", header = 0x0B70, size =  16},
			new Opcode { name = "CS_ADD_RELATION_SCORE", header = 0x0B71, size =  88},
			new Opcode { name = "CS_GET_LIKE_COUNT", header = 0x0B72, size =  16},
			new Opcode { name = "CZ_CONNECT", header = 0x0BB9, size =  1208},
			new Opcode { name = "ZC_CONNECT_OK", header = 0x0BBA, size =  0},
			new Opcode { name = "ZC_MOVE_ZONE", header = 0x0BBB, size =  7},
			new Opcode { name = "CZ_MOVE_ZONE_OK", header = 0x0BBC, size =  10},
			new Opcode { name = "ZC_CONNECT_FAILED", header = 0x0BBD, size =  0},
			new Opcode { name = "CZ_GAME_READY", header = 0x0BBE, size =  10},
			new Opcode { name = "ZC_MOVE_ZONE_OK", header = 0x0BBF, size =  57},
			new Opcode { name = "CZ_LOGOUT", header = 0x0BC0, size =  11},
			new Opcode { name = "CZ_MOVE_BARRACK", header = 0x0BC1, size =  11},
			new Opcode { name = "ZC_MOVE_BARRACK", header = 0x0BC2, size =  6},
			new Opcode { name = "ZC_LOGOUT_OK", header = 0x0BC3, size =  6},
			new Opcode { name = "ZC_MESSAGE", header = 0x0BC4, size =  0},
			new Opcode { name = "ZC_RESET_VIEW", header = 0x0BC5, size =  6},
			new Opcode { name = "ZC_START_GAME", header = 0x0BC6, size =  26},
			new Opcode { name = "ZC_QUIET", header = 0x0BC7, size =  7},
			new Opcode { name = "ZC_ENTER_PC", header = 0x0C1D, size =  353},
			new Opcode { name = "ZC_ENTER_MONSTER", header = 0x0C1E, size =  0},
			new Opcode { name = "ZC_ENTER_DUMMYPC", header = 0x0C1F, size =  316},
			new Opcode { name = "ZC_UPDATED_DUMMYPC", header = 0x0C20, size =  274},
			new Opcode { name = "ZC_ENTER_ITEM", header = 0x0C21, size =  103},
			new Opcode { name = "ZC_LEAVE", header = 0x0C22, size =  12},
			new Opcode { name = "ZC_MOVE_PATH", header = 0x0C23, size =  42},
			new Opcode { name = "ZC_MOVE_POS", header = 0x0C24, size =  43},
			new Opcode { name = "ZC_MOVE_BEZIER", header = 0x0C25, size =  75},
			new Opcode { name = "ZC_MOVE_DIR", header = 0x0C26, size =  40},
			new Opcode { name = "ZC_EXPECTED_STOPPOS", header = 0x0C27, size =  35},
			new Opcode { name = "ZC_MSPD", header = 0x0C28, size =  14},
			new Opcode { name = "ZC_MOVE_SPEED", header = 0x0C29, size =  19},
			new Opcode { name = "ZC_MOVE_STOP", header = 0x0C2A, size =  23},
			new Opcode { name = "ZC_REST_SIT", header = 0x0C2B, size =  12},
			new Opcode { name = "ZC_JUMP", header = 0x0C2C, size =  19},
			new Opcode { name = "ZC_JUMP_DIR", header = 0x0C2D, size =  34},
			new Opcode { name = "ZC_ORDER_SKILL_JUMP", header = 0x0C2E, size =  10},
			new Opcode { name = "ZC_SKILL_JUMP", header = 0x0C2F, size =  38},
			new Opcode { name = "ZC_SET_POS", header = 0x0C30, size =  23},
			new Opcode { name = "ZC_FILE_MOVE", header = 0x0C31, size =  46},
			new Opcode { name = "CZ_LEAVE_TO_DUNGEON", header = 0x0C32, size =  10},
			new Opcode { name = "ZC_UPDATED_PCAPPEARANCE", header = 0x0C33, size =  274},
			new Opcode { name = "ZC_UPDATED_MONSTERAPPEARANCE", header = 0x0C34, size =  0},
			new Opcode { name = "ZC_CHAT", header = 0x0C35, size =  0},
			new Opcode { name = "ZC_CHAT_WITH_TEXTCODE", header = 0x0C36, size =  14},
			new Opcode { name = "ZC_STANCE_CHANGE", header = 0x0C37, size =  14},
			new Opcode { name = "ZC_ADD_HP", header = 0x0C38, size =  22},
			new Opcode { name = "ZC_SKILL_CAST_CANCEL", header = 0x0C39, size =  10},
			new Opcode { name = "ZC_SKILL_CAST", header = 0x0C3A, size =  38},
			new Opcode { name = "ZC_SKILL_READY", header = 0x0C3B, size =  50},
			new Opcode { name = "ZC_SKILL_DISABLE", header = 0x0C3C, size =  15},
			new Opcode { name = "ZC_SKILL_USE_CANCEL", header = 0x0C3D, size =  10},
			new Opcode { name = "ZC_SKILL_MELEE_TARGET", header = 0x0C3E, size =  0},
			new Opcode { name = "ZC_SKILL_MELEE_GROUND", header = 0x0C3F, size =  0},
			new Opcode { name = "ZC_SKILL_FORCE_TARGET", header = 0x0C40, size =  0},
			new Opcode { name = "ZC_SKILL_FORCE_GROUND", header = 0x0C41, size =  0},
			new Opcode { name = "ZC_SKILL_HIT_INFO", header = 0x0C42, size =  0},
			new Opcode { name = "ZC_BUFF_LIST", header = 0x0C43, size =  0},
			new Opcode { name = "ZC_BUFF_ADD", header = 0x0C44, size =  0},
			new Opcode { name = "ZC_BUFF_UPDATE", header = 0x0C45, size =  0},
			new Opcode { name = "ZC_BUFF_REMOVE", header = 0x0C46, size =  20},
			new Opcode { name = "ZC_BUFF_CLEAR", header = 0x0C47, size =  11},
			new Opcode { name = "CZ_BUFF_REMOVE", header = 0x0C48, size =  14},
			new Opcode { name = "CZ_INTE_WARP", header = 0x0C49, size =  14},
			new Opcode { name = "ZC_ROTATE", header = 0x0C4A, size =  20},
			new Opcode { name = "ZC_ROTATE_RESERVED", header = 0x0C4B, size =  18},
			new Opcode { name = "ZC_HEAD_ROTATE", header = 0x0C4C, size =  18},
			new Opcode { name = "ZC_TARGET_ROTATE", header = 0x0C4D, size =  18},
			new Opcode { name = "ZC_QUICK_ROTATE", header = 0x0C4E, size =  18},
			new Opcode { name = "ZC_POSE", header = 0x0C4F, size =  34},
			new Opcode { name = "ZC_DEAD", header = 0x0C50, size =  0},
			new Opcode { name = "ZC_RESURRECT", header = 0x0C51, size =  18},
			new Opcode { name = "ZC_CHANGE_RELATION", header = 0x0C52, size =  11},
			new Opcode { name = "ZC_RESURRECT_DIALOG", header = 0x0C53, size =  7},
			new Opcode { name = "ZC_HIT_INFO", header = 0x0C54, size =  64},
			new Opcode { name = "ZC_HEAL_INFO", header = 0x0C55, size =  30},
			new Opcode { name = "ZC_CAUTION_DAMAGE_INFO", header = 0x0C57, size =  15},
			new Opcode { name = "ZC_CAUTION_DAMAGE_RELEASE", header = 0x0C58, size =  10},
			new Opcode { name = "ZC_KNOCKBACK_INFO", header = 0x0C59, size =  70},
			new Opcode { name = "ZC_KNOCKDOWN_INFO", header = 0x0C5A, size =  71},
			new Opcode { name = "CZ_RESURRECT", header = 0x0C5B, size =  19},
			new Opcode { name = "ZC_RESURRECT_SAVE_POINT_ACK", header = 0x0C5C, size =  7},
			new Opcode { name = "ZC_RESURRECT_HERE_ACK", header = 0x0C5D, size =  7},
			new Opcode { name = "CZ_CLICK_TRIGGER", header = 0x0C5E, size =  15},
			new Opcode { name = "CZ_KEYBOARD_MOVE", header = 0x0C5F, size =  41},
			new Opcode { name = "CZ_EXPECTED_STOP_POS", header = 0x0C60, size =  31},
			new Opcode { name = "CZ_JUMP", header = 0x0C61, size =  11},
			new Opcode { name = "CZ_DASHRUN", header = 0x0C62, size =  12},
			new Opcode { name = "CZ_SKILL_JUMP_REQ", header = 0x0C63, size =  30},
			new Opcode { name = "CZ_MOVE_PATH", header = 0x0C64, size =  27},
			new Opcode { name = "CZ_MOVE_STOP", header = 0x0C65, size =  35},
			new Opcode { name = "CZ_REST_SIT", header = 0x0C66, size =  10},
			new Opcode { name = "CZ_REQ_CHAR_SLOT", header = 0x0C67, size =  11},
			new Opcode { name = "CZ_ON_AIR", header = 0x0C68, size =  10},
			new Opcode { name = "CZ_ON_GROUND", header = 0x0C69, size =  10},
			new Opcode { name = "CZ_MOVEMENT_INFO", header = 0x0C6A, size =  23},
			new Opcode { name = "CZ_SKILL_TARGET", header = 0x0C6B, size =  19},
			new Opcode { name = "CZ_SKILL_TARGET_ANI", header = 0x0C6C, size =  23},
			new Opcode { name = "CZ_SKILL_GROUND", header = 0x0C6D, size =  61},
			new Opcode { name = "CZ_SKILL_SELF", header = 0x0C6E, size =  35},
			new Opcode { name = "CZ_SKILL_CANCEL", header = 0x0C6F, size =  12},
			new Opcode { name = "CZ_HOLD", header = 0x0C70, size =  11},
			new Opcode { name = "CZ_ROTATE", header = 0x0C71, size =  18},
			new Opcode { name = "CZ_HEAD_ROTATE", header = 0x0C72, size =  18},
			new Opcode { name = "CZ_TARGET_ROTATE", header = 0x0C73, size =  18},
			new Opcode { name = "CZ_POSE", header = 0x0C74, size =  34},
			new Opcode { name = "CZ_CHAT", header = 0x0C75, size =  0},
			new Opcode { name = "CZ_SELF_CHAT", header = 0x0C76, size =  0},
			new Opcode { name = "CZ_CHAT_LOG", header = 0x0C77, size =  0},
			new Opcode { name = "CZ_SHOUT", header = 0x0C78, size =  0},
			new Opcode { name = "CZ_ITEM_DROP", header = 0x0C79, size =  22},
			new Opcode { name = "CZ_ITEM_DELETE", header = 0x0C7A, size =  0},
			new Opcode { name = "CZ_ITEM_USE", header = 0x0C7B, size =  22},
			new Opcode { name = "CZ_ITEM_USE_TO_ITEM", header = 0x0C7C, size =  30},
			new Opcode { name = "CZ_ITEM_USE_TO_GROUND", header = 0x0C7D, size =  30},
			new Opcode { name = "CZ_ITEM_BUY", header = 0x0C7E, size =  0},
			new Opcode { name = "CZ_ITEM_SELL", header = 0x0C7F, size =  0},
			new Opcode { name = "CZ_ITEM_EQUIP", header = 0x0C80, size =  19},
			new Opcode { name = "CZ_ITEM_UNEQUIP", header = 0x0C81, size =  11},
			new Opcode { name = "CZ_REQ_DELETE_EXPIRED_ITEMS", header = 0x0C82, size =  18},
			new Opcode { name = "ZC_CHECK_INVINDEX", header = 0x0C83, size =  30},
			new Opcode { name = "CZ_PREMIUM_ENCHANTCHIP", header = 0x0C84, size =  26},
			new Opcode { name = "CZ_PREMIUM_GACHACUBE", header = 0x0C85, size =  10},
			new Opcode { name = "ZC_ITEM_INVENTORY_LIST", header = 0x0C86, size =  0},
			new Opcode { name = "ZC_ITEM_INVENTORY_DIVISION_LIST", header = 0x0C87, size =  0},
			new Opcode { name = "ZC_ITEM_INVENTORY_INDEX_LIST", header = 0x0C88, size =  0},
			new Opcode { name = "ZC_ITEM_EQUIP_LIST", header = 0x0C89, size =  0},
			new Opcode { name = "ZC_ITEM_ADD", header = 0x0C8A, size =  0},
			new Opcode { name = "ZC_ITEM_REMOVE", header = 0x0C8B, size =  20},
			new Opcode { name = "ZC_ITEM_USE", header = 0x0C8C, size =  14},
			new Opcode { name = "ZC_ITEM_USE_TO_GROUND", header = 0x0C8D, size =  22},
			new Opcode { name = "CZ_ITEM_ADD_WIKI", header = 0x0C8E, size =  18},
			new Opcode { name = "ZC_QUICK_SLOT_LIST", header = 0x0C8F, size =  0},
			new Opcode { name = "ZC_SKILL_LIST", header = 0x0C90, size =  0},
			new Opcode { name = "ZC_SKILL_ADD", header = 0x0C91, size =  0},
			new Opcode { name = "ZC_ABILITY_LIST", header = 0x0C92, size =  0},
			new Opcode { name = "CZ_REQ_OPEN_ITEM_DUNGEON", header = 0x0C93, size =  19},
			new Opcode { name = "CZ_ANSWER_OPEN_ITEM_DUNGEON", header = 0x0C94, size =  19},
			new Opcode { name = "CZ_SEND_ITEM_PROP_TO_ALCHMIST", header = 0x0C95, size =  28},
			new Opcode { name = "CZ_EXCUTE_ITEM_DUNGEON", header = 0x0C96, size =  34},
			new Opcode { name = "ZC_RECIVE_ITEM_PROP_TO_TARGET", header = 0x0C97, size =  0},
			new Opcode { name = "CZ_DISPEL_DEBUFF_TOGGLE", header = 0x0C98, size =  14},
			new Opcode { name = "CZ_JUNGTAN_TOGGLE", header = 0x0C99, size =  24},
			new Opcode { name = "ZC_EXP_UP", header = 0x0C9A, size =  14},
			new Opcode { name = "ZC_EXP_UP_BY_MONSTER", header = 0x0C9B, size =  18},
			new Opcode { name = "ZC_PC_LEVELUP", header = 0x0C9C, size =  14},
			new Opcode { name = "ZC_PC_STAT_AVG", header = 0x0C9D, size =  30},
			new Opcode { name = "ZC_MAX_EXP_CHANGED", header = 0x0C9E, size =  22},
			new Opcode { name = "ZC_TEXT", header = 0x0C9F, size =  0},
			new Opcode { name = "ZC_UPDATE_SP", header = 0x0CA0, size =  15},
			new Opcode { name = "ZC_RESTORATION", header = 0x0CA1, size =  12},
			new Opcode { name = "ZC_UPDATE_MHP", header = 0x0CA2, size =  14},
			new Opcode { name = "CZ_DIALOG_ACK", header = 0x0CA3, size =  14},
			new Opcode { name = "CZ_DIALOG_SELECT", header = 0x0CA4, size =  11},
			new Opcode { name = "CZ_DIALOG_STRINGINPUT", header = 0x0CA5, size =  138},
			new Opcode { name = "ZC_DIALOG_OK", header = 0x0CA6, size =  0},
			new Opcode { name = "ZC_DIALOG_NEXT", header = 0x0CA7, size =  0},
			new Opcode { name = "ZC_DIALOG_SELECT", header = 0x0CA8, size =  0},
			new Opcode { name = "ZC_DIALOG_ITEM_SELECT", header = 0x0CA9, size =  0},
			new Opcode { name = "ZC_DIALOG_CLOSE", header = 0x0CAA, size =  6},
			new Opcode { name = "ZC_DIALOG_TRADE", header = 0x0CAB, size =  39},
			new Opcode { name = "ZC_DIALOG_COMMON_TRADE", header = 0x0CAC, size =  39},
			new Opcode { name = "ZC_DIALOG_NUMBERRANGE", header = 0x0CAD, size =  0},
			new Opcode { name = "ZC_DIALOG_STRINGINPUT", header = 0x0CAE, size =  0},
			new Opcode { name = "ZC_ADDON_MSG", header = 0x0CAF, size =  0},
			new Opcode { name = "CZ_UI_EVENT", header = 0x0CB0, size =  0},
			new Opcode { name = "ZC_PLAY_SOUND", header = 0x0CB1, size =  15},
			new Opcode { name = "ZC_STOP_SOUND", header = 0x0CB2, size =  14},
			new Opcode { name = "ZC_PLAY_MUSICQUEUE", header = 0x0CB3, size =  14},
			new Opcode { name = "ZC_STOP_MUSICQUEUE", header = 0x0CB4, size =  14},
			new Opcode { name = "ZC_PLAY_ANI", header = 0x0CB5, size =  24},
			new Opcode { name = "ZC_CHANGE_ANI", header = 0x0CB6, size =  44},
			new Opcode { name = "CZ_MOVE_CAMP", header = 0x0CB7, size =  18},
			new Opcode { name = "CZ_CAMPINFO", header = 0x0CB8, size =  18},
			new Opcode { name = "ZC_CAMPINFO", header = 0x0CB9, size =  18},
			new Opcode { name = "ZC_FIX_ANIM", header = 0x0CBA, size =  14},
			new Opcode { name = "CZ_TARGET_JOB_INFO", header = 0x0CBB, size =  18},
			new Opcode { name = "ZC_TARGET_JOB_INFO", header = 0x0CBC, size =  14},
			new Opcode { name = "ZC_MOVE_ANIM", header = 0x0CBD, size =  12},
			new Opcode { name = "ZC_STD_ANIM", header = 0x0CBE, size =  11},
			new Opcode { name = "ZC_PLAY_ALARMSOUND", header = 0x0CC0, size =  83},
			new Opcode { name = "ZC_STOP_ALARMSOUND", header = 0x0CC1, size =  10},
			new Opcode { name = "ZC_PLAY_EXP_TEXT", header = 0x0CC2, size =  14},
			new Opcode { name = "ZC_PLAY_NAVI_EFFECT", header = 0x0CC3, size =  150},
			new Opcode { name = "ZC_UPDATE_ALL_STATUS", header = 0x0CC4, size =  26},
			new Opcode { name = "ZC_OBJECT_PROPERTY", header = 0x0CC5, size =  0},
			new Opcode { name = "ZC_DUMP_PROPERTY", header = 0x0CC6, size =  0},
			new Opcode { name = "ZC_SHOUT", header = 0x0CC7, size =  0},
			new Opcode { name = "ZC_SHOUT_FAILED", header = 0x0CC8, size =  7},
			new Opcode { name = "CZ_EXCHANGE_REQUEST", header = 0x0CC9, size =  14},
			new Opcode { name = "ZC_EXCHANGE_REQUEST_ACK", header = 0x0CCA, size =  72},
			new Opcode { name = "ZC_EXCHANGE_REQUEST_RECEIVED", header = 0x0CCB, size =  71},
			new Opcode { name = "CZ_EXCHANGE_ACCEPT", header = 0x0CCC, size =  10},
			new Opcode { name = "CZ_EXCHANGE_DECLINE", header = 0x0CCD, size =  10},
			new Opcode { name = "ZC_EXCHANGE_DECLINE_ACK", header = 0x0CCE, size =  6},
			new Opcode { name = "ZC_EXCHANGE_START", header = 0x0CCF, size =  72},
			new Opcode { name = "CZ_EXCHANGE_OFFER", header = 0x0CD0, size =  30},
			new Opcode { name = "ZC_EXCHANGE_OFFER_ACK", header = 0x0CD1, size =  0},
			new Opcode { name = "CZ_EXCHANGE_AGREE", header = 0x0CD2, size =  10},
			new Opcode { name = "ZC_EXCHANGE_AGREE_ACK", header = 0x0CD3, size =  7},
			new Opcode { name = "CZ_EXCHANGE_FINALAGREE", header = 0x0CD4, size =  10},
			new Opcode { name = "ZC_EXCHANGE_FINALAGREE_ACK", header = 0x0CD5, size =  7},
			new Opcode { name = "CZ_EXCHANGE_CANCEL", header = 0x0CD6, size =  10},
			new Opcode { name = "ZC_EXCHANGE_CANCEL_ACK", header = 0x0CD7, size =  6},
			new Opcode { name = "ZC_EXCHANGE_SUCCESS", header = 0x0CD8, size =  6},
			new Opcode { name = "ZC_COOLDOWN_LIST", header = 0x0CD9, size =  0},
			new Opcode { name = "ZC_COOLDOWN_CHANGED", header = 0x0CDA, size =  27},
			new Opcode { name = "ZC_OVERHEAT_CHANGED", header = 0x0CDB, size =  30},
			new Opcode { name = "ZC_TEST_AGENT", header = 0x0CDC, size =  18},
			new Opcode { name = "CZ_COMMON_SHOP_LIST", header = 0x0CDD, size =  10},
			new Opcode { name = "ZC_COMMON_SHOP_LIST", header = 0x0CDE, size =  8},
			new Opcode { name = "ZC_TIME_FACTOR", header = 0x0CDF, size =  10},
			new Opcode { name = "ZC_PARTY_ENTER", header = 0x0CE0, size =  0},
			new Opcode { name = "ZC_PARTY_OUT", header = 0x0CE1, size =  24},
			new Opcode { name = "ZC_PARTY_DESTROY", header = 0x0CE2, size =  15},
			new Opcode { name = "ZC_PARTY_INFO", header = 0x0CE3, size =  0},
			new Opcode { name = "ZC_PARTY_LIST", header = 0x0CE4, size =  0},
			new Opcode { name = "ZC_PARTY_CHAT", header = 0x0CE5, size =  0},
			new Opcode { name = "ZC_PARTY_INST_INFO", header = 0x0CE6, size =  0},
			new Opcode { name = "ZC_CHANGE_EQUIP_DURABILITY", header = 0x0CE7, size =  11},
			new Opcode { name = "CZ_DIALOG_TX", header = 0x0CE8, size =  0},
			new Opcode { name = "CZ_REQ_RECIPE", header = 0x0CE9, size =  0},
			new Opcode { name = "ZC_CUSTOM_DIALOG", header = 0x0CEA, size =  75},
			new Opcode { name = "ZC_SESSION_OBJECTS", header = 0x0CEB, size =  0},
			new Opcode { name = "ZC_SESSION_OBJ_ADD", header = 0x0CEC, size =  0},
			new Opcode { name = "ZC_SESSION_OBJ_REMOVE", header = 0x0CED, size =  10},
			new Opcode { name = "ZC_SESSION_OBJ_TIME", header = 0x0CEE, size =  14},
			new Opcode { name = "CZ_S_OBJ_VALUE_C", header = 0x0CEF, size =  26},
			new Opcode { name = "CZ_REQ_NORMAL_TX", header = 0x0CF0, size =  45},
			new Opcode { name = "ZC_COMMANDER_LOADER_INFO", header = 0x0CF1, size =  0},
			new Opcode { name = "ZC_MOVE_SINGLE_ZONE", header = 0x0CF2, size =  18},
			new Opcode { name = "ZC_BACKTO_ORIGINAL_SERVER", header = 0x0CF3, size =  8},
			new Opcode { name = "CZ_BACKTO_ORIGINAL_SERVER", header = 0x0CF4, size =  12},
			new Opcode { name = "CZ_REQ_NORMAL_TX_NUMARG", header = 0x0CF5, size =  0},
			new Opcode { name = "ZC_WIKI_LIST", header = 0x0CF6, size =  0},
			new Opcode { name = "ZC_WIKI_ADD", header = 0x0CF7, size =  22},
			new Opcode { name = "CZ_WIKI_RECIPE_UPDATE", header = 0x0CF8, size =  10},
			new Opcode { name = "ZC_UI_OPEN", header = 0x0CF9, size =  39},
			new Opcode { name = "ZC_ENABLE_CONTROL", header = 0x0CFA, size =  75},
			new Opcode { name = "ZC_CHANGE_CAMERA", header = 0x0CFB, size =  31},
			new Opcode { name = "ZC_MONSTER_SDR_CHANGED", header = 0x0CFC, size =  11},
			new Opcode { name = "ZC_MOVE_IGNORE_COLLISION", header = 0x0CFD, size =  30},
			new Opcode { name = "ZC_CHANGE_CAMERA_ZOOM", header = 0x0CFE, size =  34},
			new Opcode { name = "ZC_PLAY_SKILL_ANI", header = 0x0CFF, size =  82},
			new Opcode { name = "ZC_PLAY_SKILL_CAST_ANI", header = 0x0D00, size =  30},
			new Opcode { name = "CZ_REQ_ITEM_GET", header = 0x0D01, size =  14},
			new Opcode { name = "ZC_ITEM_GET", header = 0x0D02, size =  18},
			new Opcode { name = "CZ_GUARD", header = 0x0D03, size =  19},
			new Opcode { name = "ZC_GUARD", header = 0x0D04, size =  19},
			new Opcode { name = "ZC_STAMINA", header = 0x0D05, size =  10},
			new Opcode { name = "ZC_ADD_STAMINA", header = 0x0D06, size =  10},
			new Opcode { name = "ZC_GM_ORDER", header = 0x0D07, size =  10},
			new Opcode { name = "ZC_MYPC_ENTER", header = 0x0D08, size =  18},
			new Opcode { name = "ZC_LOCK_KEY", header = 0x0D09, size =  75},
			new Opcode { name = "ZC_SAVE_INFO", header = 0x0D0A, size =  6},
			new Opcode { name = "CZ_SAVE_INFO", header = 0x0D0B, size =  0},
			new Opcode { name = "ZC_OPTION_LIST", header = 0x0D0C, size =  0},
			new Opcode { name = "ZC_SKILLMAP_LIST", header = 0x0D0D, size =  0},
			new Opcode { name = "CZ_GIVEITEM_TO_DUMMYPC", header = 0x0D0E, size =  22},
			new Opcode { name = "CZ_FOOD_TABLE_TITLE", header = 0x0D0F, size =  79},
			new Opcode { name = "CZ_USE_TP_AND_ENTER_INDUN", header = 0x0D10, size =  522},
			new Opcode { name = "CZ_USE_RANKRESET_ITEM", header = 0x0D11, size =  18},
			new Opcode { name = "ZC_SET_LAYER", header = 0x0D12, size =  10},
			new Opcode { name = "ZC_CREATE_LAYERBOX", header = 0x0D13, size =  38},
			new Opcode { name = "ZC_RESET_BOX", header = 0x0D14, size =  11},
			new Opcode { name = "ZC_CREATE_SCROLLLOCKBOX", header = 0x0D15, size =  38},
			new Opcode { name = "ZC_REMOVE_SCROLLLOCKBOX", header = 0x0D16, size =  10},
			new Opcode { name = "CZ_DYNAMIC_CASTING_START", header = 0x0D17, size =  25},
			new Opcode { name = "CZ_DYNAMIC_CASTING_END", header = 0x0D18, size =  20},
			new Opcode { name = "CZ_SKILL_CANCEL_SCRIPT", header = 0x0D19, size =  10},
			new Opcode { name = "ZC_LEAVE_TRIGGER", header = 0x0D1A, size =  6},
			new Opcode { name = "ZC_BORN", header = 0x0D1B, size =  10},
			new Opcode { name = "ZC_ACHIEVE_POINT_LIST", header = 0x0D1C, size =  0},
			new Opcode { name = "ZC_ACHIEVE_POINT", header = 0x0D1D, size =  18},
			new Opcode { name = "CZ_ACHIEVE_EQUIP", header = 0x0D1E, size =  14},
			new Opcode { name = "ZC_ACHIEVE_EQUIP", header = 0x0D1F, size =  22},
			new Opcode { name = "CZ_ACHIEVE_REWARD", header = 0x0D20, size =  14},
			new Opcode { name = "CZ_CHANGE_CONFIG", header = 0x0D21, size =  18},
			new Opcode { name = "CZ_CHANGE_CONFIG_STR", header = 0x0D22, size =  34},
			new Opcode { name = "ZC_WORLD_MSG", header = 0x0D23, size =  43},
			new Opcode { name = "ZC_ENABLE_SHOW_ITEM_GET", header = 0x0D24, size =  8},
			new Opcode { name = "ZC_LOGIN_TIME", header = 0x0D25, size =  14},
			new Opcode { name = "ZC_GIVE_EXP_TO_PC", header = 0x0D26, size =  42},
			new Opcode { name = "ZC_LAYER_PC_LIST", header = 0x0D27, size =  0},
			new Opcode { name = "ZC_LAYER_PC_SOBJ_PROP", header = 0x0D28, size =  0},
			new Opcode { name = "CZ_CUSTOM_COMMAND", header = 0x0D29, size =  26},
			new Opcode { name = "ZC_LAYER_INFO", header = 0x0D2A, size =  10},
			new Opcode { name = "CZ_CHAT_MACRO", header = 0x0D2B, size =  146},
			new Opcode { name = "ZC_CHAT_MACRO_LIST", header = 0x0D2C, size =  0},
			new Opcode { name = "ZC_RULLET_LIST", header = 0x0D2D, size =  0},
			new Opcode { name = "ZC_QUICKSLOT_REGISTER", header = 0x0D2E, size =  46},
			new Opcode { name = "CZ_QUICKSLOT_LIST", header = 0x0D2F, size =  0},
			new Opcode { name = "CZ_DOUBLE_ITEM_EQUIP", header = 0x0D30, size =  28},
			new Opcode { name = "ZC_TRICK_PACKET", header = 0x0D31, size =  0},
			new Opcode { name = "ZC_COOLDOWN_RATE", header = 0x0D32, size =  22},
			new Opcode { name = "ZC_MAP_REVEAL_LIST", header = 0x0D33, size =  0},
			new Opcode { name = "CZ_MAP_REVEAL_INFO", header = 0x0D34, size =  146},
			new Opcode { name = "CZ_MAP_SEARCH_INFO", header = 0x0D35, size =  55},
			new Opcode { name = "ZC_EXEC_CLIENT_SCP", header = 0x0D36, size =  0},
			new Opcode { name = "ZC_SET_NPC_STATE", header = 0x0D37, size =  18},
			new Opcode { name = "ZC_NPC_STATE_LIST", header = 0x0D38, size =  0},
			new Opcode { name = "CZ_QUEST_NPC_STATE_CHECK", header = 0x0D39, size =  14},
			new Opcode { name = "ZC_RANK_ACHIEVE_ADD", header = 0x0D3A, size =  14},
			new Opcode { name = "CZ_GET_MAP_REVEAL_ACHIEVE", header = 0x0D3B, size =  10},
			new Opcode { name = "CZ_IES_MODIFY_INFO", header = 0x0D3C, size =  0},
			new Opcode { name = "ZC_IES_MODIFY_INFO", header = 0x0D3D, size =  0},
			new Opcode { name = "ZC_IES_MODIFY_LIST", header = 0x0D3E, size =  0},
			new Opcode { name = "CZ_IES_REVISION_DELETE", header = 0x0D3F, size =  0},
			new Opcode { name = "ZC_IES_REVISION_DELETE", header = 0x0D40, size =  0},
			new Opcode { name = "ZC_EQUIP_ITEM_REMOVE", header = 0x0D41, size =  18},
			new Opcode { name = "ZC_SOLD_ITEM_LIST", header = 0x0D42, size =  0},
			new Opcode { name = "ZC_SOLD_ITEM_DIVISION_LIST", header = 0x0D43, size =  0},
			new Opcode { name = "CZ_SOLD_ITEM", header = 0x0D44, size =  19},
			new Opcode { name = "CZ_WAREHOUSE_CMD", header = 0x0D45, size =  32},
			new Opcode { name = "CZ_SWAP_ETC_INV_CHANGE_INDEX", header = 0x0D46, size =  35},
			new Opcode { name = "CZ_SORT_INV", header = 0x0D47, size =  12},
			new Opcode { name = "CZ_EXTEND_WAREHOUSE", header = 0x0D48, size =  11},
			new Opcode { name = "CZ_CAST_CONTROL_SHOT", header = 0x0D49, size =  10},
			new Opcode { name = "ZC_PC_PROP_UPDATE", header = 0x0D4A, size =  11},
			new Opcode { name = "CZ_CLIENT_DAMAGE", header = 0x0D4B, size =  14},
			new Opcode { name = "CZ_CLIENT_ATTACK", header = 0x0D4C, size =  15},
			new Opcode { name = "ZC_SYSTEM_MSG", header = 0x0D4D, size =  0},
			new Opcode { name = "ZC_FSM_MOVE", header = 0x0D4E, size =  0},
			new Opcode { name = "CZ_QUEST_CHECK_SAVE", header = 0x0D4F, size =  50},
			new Opcode { name = "CZ_SPRAY_REQ_INFO", header = 0x0D50, size =  14},
			new Opcode { name = "CZ_SPRAY_DRAW_INFO", header = 0x0D51, size =  0},
			new Opcode { name = "ZC_SPRAY_ID", header = 0x0D52, size =  18},
			new Opcode { name = "ZC_SPRAY_DRAW_INFO", header = 0x0D53, size =  0},
			new Opcode { name = "ZC_MONSTER_LIFETIME", header = 0x0D54, size =  14},
			new Opcode { name = "ZC_SPRAY_LIKE_LIST", header = 0x0D55, size =  0},
			new Opcode { name = "ZC_WIKI_COUNT_UPDATE", header = 0x0D56, size =  19},
			new Opcode { name = "ZC_WIKI_INT_PROP_UPDATE", header = 0x0D57, size =  15},
			new Opcode { name = "ZC_WIKI_BOOL_PROP_UPDATE", header = 0x0D58, size =  12},
			new Opcode { name = "CZ_REQ_WIKI_RANK", header = 0x0D59, size =  15},
			new Opcode { name = "ZC_WIKI_RANK_LIST", header = 0x0D5A, size =  0},
			new Opcode { name = "ZC_SHARED_MSG", header = 0x0D5B, size =  10},
			new Opcode { name = "CZ_REQ_WIKI_PROP_RANK", header = 0x0D5C, size =  16},
			new Opcode { name = "CZ_GET_WIKI_REWARD", header = 0x0D5D, size =  11},
			new Opcode { name = "CZ_REQ_TX_ITEM", header = 0x0D5E, size =  0},
			new Opcode { name = "ZC_TEST_DBG", header = 0x0D5F, size =  0},
			new Opcode { name = "ZC_MONSTER_DIST", header = 0x0D60, size =  0},
			new Opcode { name = "ZC_RESET_SKILL_FORCEID", header = 0x0D61, size =  10},
			new Opcode { name = "ZC_EMOTICON", header = 0x0D62, size =  18},
			new Opcode { name = "ZC_SHOW_EMOTICON", header = 0x0D63, size =  18},
			new Opcode { name = "ZC_TREASUREMARK_BY_MAP", header = 0x0D64, size =  0},
			new Opcode { name = "ZC_SHOW_MAP", header = 0x0D65, size =  0},
			new Opcode { name = "CZ_FLEE_OBSTACLE", header = 0x0D66, size =  26},
			new Opcode { name = "ZC_HOLD_MOVE_PATH", header = 0x0D67, size =  11},
			new Opcode { name = "ZC_ENTER_HOOK", header = 0x0D68, size =  10},
			new Opcode { name = "ZC_LEAVE_HOOK", header = 0x0D69, size =  10},
			new Opcode { name = "ZC_MONSTER_PROPERTY", header = 0x0D6A, size =  0},
			new Opcode { name = "ZC_GROUND_EFFECT", header = 0x0D6B, size =  50},
			new Opcode { name = "ZC_FLY", header = 0x0D6C, size =  18},
			new Opcode { name = "ZC_FLY_OPTION", header = 0x0D6D, size =  14},
			new Opcode { name = "ZC_FLY_MATH", header = 0x0D6E, size =  23},
			new Opcode { name = "ZC_FLY_HEIGHT", header = 0x0D6F, size =  14},
			new Opcode { name = "ZC_UPDATE_SHIELD", header = 0x0D70, size =  14},
			new Opcode { name = "ZC_SHOW_MODEL", header = 0x0D71, size =  15},
			new Opcode { name = "ZC_SKILL_RANGE_DBG", header = 0x0D72, size =  58},
			new Opcode { name = "ZC_SKILL_RANGE_FAN", header = 0x0D73, size =  40},
			new Opcode { name = "ZC_SKILL_RANGE_SQUARE", header = 0x0D74, size =  40},
			new Opcode { name = "ZC_SKILL_RANGE_CIRCLE", header = 0x0D75, size =  28},
			new Opcode { name = "ZC_SKILL_RANGE_DONUTS", header = 0x0D76, size =  32},
			new Opcode { name = "ZC_TEAMID", header = 0x0D77, size =  11},
			new Opcode { name = "ZC_PC", header = 0x0D78, size =  0},
			new Opcode { name = "CZ_LOG", header = 0x0D79, size =  0},
			new Opcode { name = "ZC_MOTIONBLUR", header = 0x0D7A, size =  11},
			new Opcode { name = "ZC_PLAY_FORCE", header = 0x0D7B, size =  78},
			new Opcode { name = "ZC_CAST_TARGET", header = 0x0D7C, size =  14},
			new Opcode { name = "ZC_START_INFO", header = 0x0D7D, size =  0},
			new Opcode { name = "ZC_JOB_EXP_UP", header = 0x0D7E, size =  18},
			new Opcode { name = "ZC_JOB_PTS", header = 0x0D7F, size =  18},
			new Opcode { name = "ZC_MON_STAMINA", header = 0x0D80, size =  22},
			new Opcode { name = "CZ_CUSTOM_SCP", header = 0x0D81, size =  14},
			new Opcode { name = "ZC_VIEW_FOCUS", header = 0x0D82, size =  24},
			new Opcode { name = "ZC_HARDCODED_SKILL", header = 0x0D83, size =  26},
			new Opcode { name = "CZ_HARDCODED_SKILL", header = 0x0D84, size =  34},
			new Opcode { name = "ZC_FORCE_MOVE", header = 0x0D85, size =  30},
			new Opcode { name = "ZC_HSKILL_CONTROL", header = 0x0D86, size =  22},
			new Opcode { name = "ZC_CANCEL_DEADEVENT", header = 0x0D87, size =  10},
			new Opcode { name = "ZC_ACTION_PKS", header = 0x0D88, size =  35},
			new Opcode { name = "CZ_HARDCODED_ITEM", header = 0x0D89, size =  22},
			new Opcode { name = "CZ_CANCEL_TRANSFORM_SKILL", header = 0x0D8A, size =  10},
			new Opcode { name = "CZ_BRIQUET", header = 0x0D8B, size =  32},
			new Opcode { name = "ZC_VIBRATE", header = 0x0D8C, size =  30},
			new Opcode { name = "ZC_COUNTER_MOVE", header = 0x0D8D, size =  10},
			new Opcode { name = "CZ_COUNTER_ATTACK", header = 0x0D8E, size =  14},
			new Opcode { name = "CZ_CLIENT_DIRECT", header = 0x0D8F, size =  30},
			new Opcode { name = "ZC_CLIENT_DIRECT", header = 0x0D90, size =  30},
			new Opcode { name = "ZC_OWNER", header = 0x0D91, size =  14},
			new Opcode { name = "ZC_GD_RANK", header = 0x0D92, size =  10},
			new Opcode { name = "CZ_RUN_BGEVENT", header = 0x0D93, size =  74},
			new Opcode { name = "ZC_ADD_SKILL_EFFECT", header = 0x0D94, size =  18},
			new Opcode { name = "ZC_ITEM_DROPABLE", header = 0x0D95, size =  10},
			new Opcode { name = "CZ_ITEM_DROP_TO_OBJECT", header = 0x0D96, size =  26},
			new Opcode { name = "ZC_NORMAL", header = 0x0D97, size =  0},
			new Opcode { name = "CZ_G_QUEST_CHECK", header = 0x0D98, size =  14},
			new Opcode { name = "ZC_MOVE_PATH_MATH", header = 0x0D99, size =  30},
			new Opcode { name = "CZ_MYPAGE_COMMENT_ADD", header = 0x0D9A, size =  278},
			new Opcode { name = "CZ_MYPAGE_COMMENT_DELETE", header = 0x0D9B, size =  18},
			new Opcode { name = "CZ_GUESTPAGE_COMMENT_ADD", header = 0x0D9C, size =  278},
			new Opcode { name = "CZ_GET_TARGET_MYPAGE", header = 0x0D9D, size =  14},
			new Opcode { name = "CZ_ON_MYPAGE_MODE", header = 0x0D9E, size =  14},
			new Opcode { name = "CZ_RESET_SOCIAL_MODE", header = 0x0D9F, size =  10},
			new Opcode { name = "CZ_GET_TARGET_GUESTPAGE", header = 0x0DA0, size =  14},
			new Opcode { name = "CZ_ADD_SELLMODE_ITEM", header = 0x0DA1, size =  30},
			new Opcode { name = "CZ_DELETE_SELLMODE_ITEM", header = 0x0DA2, size =  18},
			new Opcode { name = "CZ_ON_SELLITEM_MODE", header = 0x0DA3, size =  14},
			new Opcode { name = "ZC_MYPAGE_MAP", header = 0x0DA4, size =  0},
			new Opcode { name = "ZC_GUESTPAGE_MAP", header = 0x0DA5, size =  0},
			new Opcode { name = "ZC_ON_MYPAGE_MODE", header = 0x0DA6, size =  0},
			new Opcode { name = "ZC_RESET_SOCIAL_MODE", header = 0x0DA7, size =  10},
			new Opcode { name = "CZ_ON_ITEMBUY_MODE", header = 0x0DA8, size =  0},
			new Opcode { name = "ZC_ON_BUYITEM_MODE", header = 0x0DA9, size =  0},
			new Opcode { name = "ZC_SHOW_GROUND_ITEM_MARK", header = 0x0DAA, size =  30},
			new Opcode { name = "ZC_HELP_LIST", header = 0x0DAB, size =  0},
			new Opcode { name = "ZC_HELP_ADD", header = 0x0DAC, size =  11},
			new Opcode { name = "CZ_CLIENT_HIT_LIST", header = 0x0DAD, size =  0},
			new Opcode { name = "ZC_PC_ATKSTATE", header = 0x0DAE, size =  11},
			new Opcode { name = "ZC_SEND_PREMIUM_STATE", header = 0x0DAF, size =  16},
			new Opcode { name = "CZ_HELP_READ_TYPE", header = 0x0DB0, size =  18},
			new Opcode { name = "CZ_MOVE_PATH_END", header = 0x0DB1, size =  10},
			new Opcode { name = "ZC_COLL_DAMAGE", header = 0x0DB2, size =  11},
			new Opcode { name = "CZ_KEYBOARD_BEAT", header = 0x0DB3, size =  10},
			new Opcode { name = "CZ_MOVEHIT_SCP", header = 0x0DB4, size =  22},
			new Opcode { name = "ZC_SYNC_START", header = 0x0DB5, size =  14},
			new Opcode { name = "ZC_SYNC_END", header = 0x0DB6, size =  14},
			new Opcode { name = "ZC_SYNC_EXEC", header = 0x0DB7, size =  10},
			new Opcode { name = "ZC_SYNC_EXEC_BY_SKILL_TIME", header = 0x0DB8, size =  18},
			new Opcode { name = "CZ_STOP_TIMEACTION", header = 0x0DB9, size =  11},
			new Opcode { name = "CZ_REQ_DUMMYPC_INFO", header = 0x0DBA, size =  18},
			new Opcode { name = "CZ_VISIT_BARRACK", header = 0x0DBB, size =  74},
			new Opcode { name = "CZ_SPC_SKILL_POS", header = 0x0DBC, size =  22},
			new Opcode { name = "CZ_CHANGE_HEAD", header = 0x0DBD, size =  74},
			new Opcode { name = "CZ_CREATE_ARROW_CRAFT", header = 0x0DBE, size =  14},
			new Opcode { name = "CZ_REQ_MINITEXT", header = 0x0DBF, size =  266},
			new Opcode { name = "ZC_PC_MOVE_STOP", header = 0x0DC0, size =  35},
			new Opcode { name = "CZ_STOP_ALLPC", header = 0x0DC1, size =  10},
			new Opcode { name = "CZ_COMPLETE_PRELOAD", header = 0x0DC2, size =  14},
			new Opcode { name = "CZ_MGAME_JOIN_CMD", header = 0x0DC3, size =  46},
			new Opcode { name = "CZ_ADD_HELP", header = 0x0DC4, size =  14},
			new Opcode { name = "ZC_ATTACH_TO_OBJ", header = 0x0DC5, size =  49},
			new Opcode { name = "ZC_DETACH_FROM_OBJ", header = 0x0DC6, size =  14},
			new Opcode { name = "ZC_RUN_FROM", header = 0x0DC7, size =  14},
			new Opcode { name = "ZC_LOOKAT_OBJ", header = 0x0DC8, size =  14},
			new Opcode { name = "CZ_SKILL_CELL_LIST", header = 0x0DC9, size =  0},
			new Opcode { name = "CZ_SKILL_TOOL_GROUND_POS", header = 0x0DCA, size =  26},
			new Opcode { name = "CZ_DIRECTION_PROCESS", header = 0x0DCB, size =  18},
			new Opcode { name = "CZ_DIRECTION_MOVE_STATE", header = 0x0DCC, size =  0},
			new Opcode { name = "ZC_TO_ALL_CLIENT", header = 0x0DCD, size =  0},
			new Opcode { name = "ZC_TO_CLIENT", header = 0x0DCE, size =  0},
			new Opcode { name = "CZ_REWARD_CMD", header = 0x0DCF, size =  14},
			new Opcode { name = "CZ_PROPERTY_COMPARE", header = 0x0DD0, size =  16},
			new Opcode { name = "ZC_PROPERTY_COMPARE", header = 0x0DD1, size =  0},
			new Opcode { name = "ZC_PROPERTY_COMPARE_FOR_ACT", header = 0x0DD2, size =  0},
			new Opcode { name = "ZC_FACTION", header = 0x0DD3, size =  14},
			new Opcode { name = "ZC_SEND_CASH_VALUE", header = 0x0DD4, size =  0},
			new Opcode { name = "ZC_BEGIN_KILL_LOG", header = 0x0DD5, size =  6},
			new Opcode { name = "ZC_END_KILL_LOG", header = 0x0DD6, size =  6},
			new Opcode { name = "ZC_CLEAR_KILL_LOG", header = 0x0DD7, size =  6},
			new Opcode { name = "CZ_NPC_AUCTION_CMD", header = 0x0DD8, size =  30},
			new Opcode { name = "ZC_DIRECTION_APC", header = 0x0DD9, size =  26},
			new Opcode { name = "ZC_BGMODEL_ANIM_INFO", header = 0x0DDA, size =  15},
			new Opcode { name = "ZC_ATTACH_BY_KNOCKBACK", header = 0x0DDB, size =  38},
			new Opcode { name = "CZ_OBJECT_MOVE", header = 0x0DDC, size =  30},
			new Opcode { name = "CZ_CONTROL_OBJECT_ROTATE", header = 0x0DDD, size =  22},
			new Opcode { name = "CZ_SUMMON_COMMAND", header = 0x0DDE, size =  18},
			new Opcode { name = "CZ_VEHICLE_RIDE", header = 0x0DDF, size =  15},
			new Opcode { name = "CZ_REQ_WIKI_CATEGORY_RANK_PAGE_INFO", header = 0x0DE0, size =  78},
			new Opcode { name = "CZ_REQ_ACHIEVE_RANK_PAGE_INFO", header = 0x0DE1, size =  78},
			new Opcode { name = "CZ_REQ_MONSTER_RANK_INFO", header = 0x0DE2, size =  74},
			new Opcode { name = "ZC_SPC_TRIGGER_EXEC", header = 0x0DE3, size =  30},
			new Opcode { name = "CZ_REQ_MGAME_VIEW", header = 0x0DE4, size =  18},
			new Opcode { name = "CZ_REQ_MGAME_CHAT", header = 0x0DE5, size =  0},
			new Opcode { name = "CZ_TOURNAMENT_GIFT", header = 0x0DE6, size =  18},
			new Opcode { name = "CZ_PARTY_INVITE_ACCEPT", header = 0x0DE7, size =  87},
			new Opcode { name = "CZ_PARTY_INVITE_CANCEL", header = 0x0DE8, size =  91},
			new Opcode { name = "CZ_PARTY_PROP_CHANGE", header = 0x0DE9, size =  147},
			new Opcode { name = "CZ_REQ_MARKET_REGISTER", header = 0x0DEA, size =  40},
			new Opcode { name = "CZ_REQ_MARKET_MINMAX_INFO", header = 0x0DEB, size =  18},
			new Opcode { name = "CZ_REQ_MARKET_BUY", header = 0x0DEC, size =  0},
			new Opcode { name = "CZ_REQ_MARKET_LIST", header = 0x0DED, size =  138},
			new Opcode { name = "CZ_REQ_MY_SELL_LIST", header = 0x0DEE, size =  14},
			new Opcode { name = "CZ_REQ_CABINET_LIST", header = 0x0DEF, size =  10},
			new Opcode { name = "CZ_REQ_GET_CABINET_ITEM", header = 0x0DF0, size =  26},
			new Opcode { name = "CZ_REQ_CANCEL_MARKET_ITEM", header = 0x0DF1, size =  18},
			new Opcode { name = "CZ_INV_ITEM_LOCK", header = 0x0DF2, size =  19},
			new Opcode { name = "CZ_OBJ_RECORD_POS", header = 0x0DF3, size =  0},
			new Opcode { name = "CZ_FORMATION_CMD", header = 0x0DF4, size =  32},
			new Opcode { name = "CZ_REGISTER_AUTOSELLER", header = 0x0DF5, size =  0},
			new Opcode { name = "CZ_OPEN_AUTOSELLER", header = 0x0DF6, size =  66},
			new Opcode { name = "CZ_BUY_AUTOSELLER_ITEMS", header = 0x0DF7, size =  0},
			new Opcode { name = "CZ_SELL_MY_AUTOSELLER_ITEMS", header = 0x0DF8, size =  0},
			new Opcode { name = "CZ_PUZZLE_CRAFT", header = 0x0DF9, size =  0},
			new Opcode { name = "CZ_PET_EQUIP", header = 0x0DFA, size =  34},
			new Opcode { name = "CZ_PET_AUTO_ATK", header = 0x0DFB, size =  11},
			new Opcode { name = "ZC_PET_AUTO_ATK", header = 0x0DFC, size =  11},
			new Opcode { name = "ZC_FOUND_PARTY_LIST", header = 0x0DFD, size =  0},
			new Opcode { name = "ZC_NEAR_PARTY_LIST", header = 0x0DFE, size =  0},
			new Opcode { name = "ZC_RECOMMEND_PARTY_INFO", header = 0x0DFF, size =  0},
			new Opcode { name = "CZ_REQUEST_SOME_PARTY", header = 0x0E00, size =  90},
			new Opcode { name = "CZ_REFRESH_MEMBERRECOMMEND_LIST", header = 0x0E01, size =  10},
			new Opcode { name = "ZC_TO_SOMEWHERE_CLIENT", header = 0x0E02, size =  0},
			new Opcode { name = "CZ_REVEAL_NPC_STATE", header = 0x0E03, size =  14},
			new Opcode { name = "CZ_CHANGE_CHANNEL", header = 0x0E04, size =  12},
			new Opcode { name = "CZ_REQ_CHANNEL_TRAFFICS", header = 0x0E05, size =  12},
			new Opcode { name = "CZ_BUY_PROPERTYSHOP_ITEM", header = 0x0E06, size =  0},
			new Opcode { name = "CZ_SKILL_USE_HEIGHT", header = 0x0E07, size =  14},
			new Opcode { name = "CZ_ACCEPT_PARTY_QUEST", header = 0x0E08, size =  20},
			new Opcode { name = "CZ_CHANGE_GUILD_NEUTRALITY", header = 0x0E09, size =  10},
			new Opcode { name = "CZ_SAVE_GUILD_BOARD", header = 0x0E0A, size =  110},
			new Opcode { name = "CZ_ACCEPT_PARTY_EVENT", header = 0x0E0B, size =  20},
			new Opcode { name = "CZ_DELETE_PARTY_EVENT", header = 0x0E0C, size =  20},
			new Opcode { name = "CZ_PING", header = 0x0E0D, size =  10},
			new Opcode { name = "ZC_PING", header = 0x0E0E, size =  10},
			new Opcode { name = "CZ_REQ_REMAIN_NEXONCASH", header = 0x0E0F, size =  10},
			new Opcode { name = "CZ_REQ_OPEN_INGAMESHOP_UI", header = 0x0E10, size =  10},
			new Opcode { name = "CZ_REQ_BUY_INGAMESHOP_ITEM", header = 0x0E11, size =  78},
			new Opcode { name = "CZ_REQ_BUY_ALL_INGAMESHOP_ITEM", header = 0x0E12, size =  10},
			new Opcode { name = "CZ_REQ_PICKUP_CASHITEM", header = 0x0E13, size =  37},
			new Opcode { name = "CZ_REQ_REFUND_CASHITEM", header = 0x0E14, size =  33},
			new Opcode { name = "ZC_XIGNCODE_BUFFER", header = 0x0E15, size =  524},
			new Opcode { name = "CZ_XIGNCODE_BUFFER", header = 0x0E16, size =  524},
			new Opcode { name = "CZ_SYSTEM_LOG_SAVE_TO_MONGODB", header = 0x0E17, size =  280},
			new Opcode { name = "CZ_CHANGE_TITLE", header = 0x0E18, size =  74},
			new Opcode { name = "CZ_PC_COMMENT_CHANGE", header = 0x0E19, size =  0},
			new Opcode { name = "CZ_AUTTOSELLER_BUYER_CLOSE", header = 0x0E1A, size =  18},
			new Opcode { name = "CZ_REQ_ITEM_LIST", header = 0x0E1B, size =  11},
			new Opcode { name = "CZ_REQ_ACC_WARE_VIS_LOG", header = 0x0E1C, size =  10},
			new Opcode { name = "CZ_HIT_MISSILE", header = 0x0E1D, size =  14},
			new Opcode { name = "CZ_I_NEED_PARTY", header = 0x0E1E, size =  23},
			new Opcode { name = "CZ_PARTY_JOIN_BY_LINK", header = 0x0E1F, size =  19},
			new Opcode { name = "ZC_RECOMMEND_PARTYMEMBER_INFO", header = 0x0E20, size =  0},
			new Opcode { name = "CZ_PVP_ZONE_CMD", header = 0x0E21, size =  26},
			new Opcode { name = "CZ_PVP_CHAT", header = 0x0E22, size =  0},
			new Opcode { name = "CZ_CARDBATTLE_CMD", header = 0x0E23, size =  26},
			new Opcode { name = "CZ_REQ_UPDATE_CONTENTS_SESSION", header = 0x0E24, size =  10},
			new Opcode { name = "CZ_REQ_FRIENDLY_FIGHT", header = 0x0E25, size =  15},
			new Opcode { name = "CZ_HARDSKILL_POS_LIST", header = 0x0E26, size =  0},
			new Opcode { name = "CZ_CART_POSITION", header = 0x0E27, size =  26},
			new Opcode { name = "CZ_REQ_RIDE_CART", header = 0x0E28, size =  18},
			new Opcode { name = "CZ_DUMMYPC_SKILL_POS", header = 0x0E29, size =  26},
			new Opcode { name = "CZ_NGS", header = 0x0E2A, size =  0},
			new Opcode { name = "CZ_PARTY_MEMBER_SKILL_USE", header = 0x0E2B, size =  0},
			new Opcode { name = "CZ_PARTY_MEMBER_SKILL_ACCEPT", header = 0x0E2C, size =  22},
			new Opcode { name = "CZ_SYSTEM_LOG_TO_SERVER", header = 0x0E2D, size =  1099},
			new Opcode { name = "CZ_CHECK_PING", header = 0x0E2E, size =  10},
			new Opcode { name = "CZ_CANCEL_INDUN_MATCHING", header = 0x0E2F, size =  10},
			new Opcode { name = "CZ_CANCEL_INDUN_PARTY_MATCHING", header = 0x0E30, size =  10},
			new Opcode { name = "CZ_REQ_GM_ORDER", header = 0x0E31, size =  202},
			new Opcode { name = "CZ_REPORT_AUTOBOT", header = 0x0E32, size =  74},
			new Opcode { name = "CZ_REPORT_PVP_ZOOM", header = 0x0E33, size =  10},
			new Opcode { name = "CZ_PARTY_INVENTORY_LOAD", header = 0x0E34, size =  12},
			new Opcode { name = "CZ_PARTY_SHARED_QUEST", header = 0x0E35, size =  278},
			new Opcode { name = "CZ_REQ_MOVE_PARTYINV_TO_ACCOUNT", header = 0x0E36, size =  31},
			new Opcode { name = "CZ_PVP_COMMAND", header = 0x0E37, size =  23},
			new Opcode { name = "CZ_REQ_CancelGachaCube", header = 0x0E38, size =  10},
			new Opcode { name = "CZ_WAREHOUSE_TAKE_LIST", header = 0x0E39, size =  0},
			new Opcode { name = "CZ_SAVE_AUTO_MACRO", header = 0x0E3A, size =  0},
			new Opcode { name = "CZ_REQUEST_LOAD_ITEM_BUY_LIMIT", header = 0x0E3B, size =  10},
			new Opcode { name = "CZ_AUTO_STATE", header = 0x0E3C, size =  11},
			new Opcode { name = "CZ_RUN_GAMEEXIT_TIMER", header = 0x0E3D, size =  42},
			new Opcode { name = "CZ_FIXED_NOTICE_SHOW", header = 0x0E3E, size =  10},
			new Opcode { name = "CZ_SAGE_SKILL_GO_FRIEND", header = 0x0E3F, size =  90},
			new Opcode { name = "CZ_REQUEST_CHANGE_NAME", header = 0x0E40, size =  66},
			new Opcode { name = "ZC_HOLD_EXP_BOOK_TIME", header = 0x0E41, size =  25},
			new Opcode { name = "CZ_HOLD_EXP_BOOK_TIME", header = 0x0E42, size =  14},
			new Opcode { name = "CZ_SCREENSHOT_HASH", header = 0x0E43, size =  43},
			new Opcode { name = "CZ_REQ_MOVE_TO_INDUN", header = 0x0E44, size =  18},
			new Opcode { name = "CZ_CLEAR_INDUN_REG", header = 0x0E45, size =  10},
			new Opcode { name = "CZ_REQ_REGISTER_TO_INDUN", header = 0x0E46, size =  14},
			new Opcode { name = "CZ_REQ_GUILD_MEMBER_AUTHORITY", header = 0x0E47, size =  23},
			new Opcode { name = "CZ_TPSHOP_RTPP_FOR_TEST", header = 0x0E48, size =  10},
			new Opcode { name = "CZ_REQ_FORGERY", header = 0x0E49, size =  30},
			new Opcode { name = "CZ_REQ_BUILD_FOODTABLE", header = 0x0E4A, size =  79},
			new Opcode { name = "CZ_REQ_UNDERSTAFF_ENTER_ALLOW", header = 0x0E4B, size =  10},
			new Opcode { name = "CZ_REQ_UNDERSTAFF_ENTER_ALLOW_WITH_PARTY", header = 0x0E4C, size =  14},
			new Opcode { name = "ZC_PLAY_PAIR_ANIMATION", header = 0x0E4D, size =  34},
			new Opcode { name = "ZC_ATTACH_TO_SLOT", header = 0x0E4E, size =  22},
			new Opcode { name = "CZ_REQ_FISHING", header = 0x0E4F, size =  23},
			new Opcode { name = "CZ_REQ_GET_FISHING_ITEM", header = 0x0E50, size =  10},
			new Opcode { name = "ZC_PLAY_ATTACH_MODEL_ANIM", header = 0x0E51, size =  22},
			new Opcode { name = "ZC_FISHING_ITEM_LIST", header = 0x0E52, size =  0},
			new Opcode { name = "CZ_REQ_FISHING_RANK", header = 0x0E53, size =  78},
			new Opcode { name = "ZC_ENABLE_ROTATE", header = 0x0E54, size =  75},
			new Opcode { name = "CZ_SYNC_POS", header = 0x0E55, size =  26},
			new Opcode { name = "CZ_DISCONNECT_REASON_FOR_LOG", header = 0x0E56, size =  0},
			new Opcode { name = "CZ_LOAD_COMPLETE", header = 0x0E57, size =  10},
			new Opcode { name = "ZC_LOAD_COMPLETE", header = 0x0E58, size =  6 }
		};
		#endregion opcodes

		/// <summary>
		/// Describes the packet structure for the BC_START_GAMEOK opcode.
		/// </summary>
		public class StartGamePacket
		{
			public static readonly string name = "BC_START_GAMEOK";

			#region structure
			public byte[] header = new byte[6];
			public byte[] unk_1 = new byte[4];
			public byte[] address = new byte[4];
			public byte[] port = new byte[4];
			public byte[] unk_2;
			#endregion structure

			/// <summary>
			/// Shifts bytes from a buffer into smaller chunks of class properties.
			/// </summary>
			/// <param name="buffer">A BC_START_GAMEOK packet</param>
			public StartGamePacket(byte[] buffer)
			{
				this.header = buffer.Take(this.header.Length).ToArray();
				buffer = buffer.Skip(this.header.Length).ToArray();

				this.unk_1 = buffer.Take(this.unk_1.Length).ToArray();
				buffer = buffer.Skip(this.unk_1.Length).ToArray();

				this.address = buffer.Take(this.address.Length).ToArray();
				buffer = buffer.Skip(this.address.Length).ToArray();

				this.port = buffer.Take(this.port.Length).ToArray();
				buffer = buffer.Skip(this.port.Length).ToArray();

				this.unk_2 = buffer.ToArray();
			}

			/// <summary>
			/// Returns a built byte array of all properties.
			/// </summary>
			/// <returns></returns>
			public byte[] Build()
			{
				return this.header
					.Concat(this.unk_1)
					.Concat(this.address)
					.Concat(this.port)
					.Concat(this.unk_2)
					.ToArray();
			}
		}
	}
}
